AWSTemplateFormatVersion: "2010-09-09"
Description: Prometheus + Grafana Monitoring Server (Amazon Linux 2023)

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Existing VPC ID

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet ID in the VPC

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair for SSH access

Resources:
  PrometheusEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: prometheus-ec2-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
  PrometheusDiscoveryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: prometheus-ec2-discovery
      Roles:
        - !Ref PrometheusEC2Role
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:DescribeInstances
              - ec2:DescribeRegions
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeTags
            Resource: "*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: prometheus-ec2-profile
      Roles:
        - !Ref PrometheusEC2Role

  MonitoringSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Prometheus and Grafana access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0

  PrometheusEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0b46816ffa1234887 # Amazon Linux 2023 (eu-north-1)
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref MonitoringSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile

      Tags:
        - Key: Name
          Value: prometheus-monitoring
        - Key: Monitor
          Value: true


