name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4


      - name: Update CloudFormation stack
        shell: bash
        run: |
          STACK_NAME="dashen-app-stack"
          REGION="eu-north-1"

          aws cloudformation create-stack \
            --stack-name $STACK_NAME \
            --region $REGION \
            --template-body file://templates/web-stack.yaml \
            --parameters file://params/dev.json
            --capabilities CAPABILITY_NAMED_IAM
