name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4


      - name: Update CloudFormation stack
        shell: bash
        run: |
          STACK_NAME="promotheus-monitoring-stack"
          REGION="eu-north-1"

          aws cloudformation create-stack \
            --stack-name $STACK_NAME \
            --region $REGION \
            --template-body file://promotheus-stack/templates/prometheus-monitoring.yaml \
            --parameters file://promotheus-stack/params/dev.json \
            --capabilities CAPABILITY_NAMED_IAM


